### PR TITLE
Motion Timestamp and Sensitivity Scaling

### LINKED ISSUE #32: Gyroscope doesn't work well in Infamous: Second Son
Gyroscope doesn't work well in Infamous: Second Son

Related: http://www.youtube.com/watch?v=As4Jbf6Wu-M

### PR DESCRIPTION
**Pull request by the-maazu**
Possible fix #32.

Works well with motion aiming in "Days Gone".

Recommended default motion config:

[Motion]
Activate=1
Port=5555
Sens=50
AccelSens=50
GyroSens=50
InverseX=1
InverseY=0
InverseZ=1
SleepTimeOut=1
Orientation=1

### CODE REVIEW

**Comment by r57zone** [comment]
Cool! Thank you! I will merge soon.

**Comment by r57zone** [comment]
Could you please confirm if there is a problem with the battery reading? One user wrote that the battery status is low.
Do you have such a problem? 

BatteryLvl seems to be equal to 8 and the second status to some other value.
```
//report.bBatteryLvl = 8;
//report.bBatteryLvlSpecial = 32; ??? not working
```

**Comment by the-maazu** [comment]
> Cool! Thank you! I will merge soon.

Yes works well, with Detroit: Become Human too, orientation detection works, the extra 5 bytes are speculated arent needed at all.


> Could you please confirm if there is a problem with the battery reading? [One user](https://github.com/r57zone/DualShock4-emulator/issues/53) wrote that the battery status is low. Do you have such a problem?
> 
> BatteryLvl seems to be equal to 8 and the second status to some other value.
> 
> ```
> //report.bBatteryLvl = 8;
> //report.bBatteryLvlSpecial = 32; ??? not working
> ```

Will take a look.

Also the PS Plus seems to be prioritizing Xbox Controller, maybe you should recommend using [HidHide](https://github.com/ViGEm/HidHide) it works fine.

**Comment by r57zone** [comment]
I updated the binaries, thanks for pr and improvement!
https://github.com/r57zone/DualShock4-emulator/releases

**Pull request merged**
