### PR TITLE
Mouse movement is smoother

### PR DESCRIPTION
**Pull request by Hathanhks**
Mouse movement is smoother when moving slowly

### CODE REVIEW

**Comment by r57zone** [comment]
Hi, how did you notice a smoother operation?

**Comment by Hathanhks** [comment]
when moving the mouse slowly, the Right joystick can move but the x and y axes will still be in the deadzone (110<->140) causing the camera not to move, this needs to move the mouse faster for the Right joystick to pass the deadzone , this hover will be inaccurate and will feel a big delay

**Comment by Hathanhks** [comment]
when moving the mouse slowly, the Right joystick can move but the x and y axes will still be in the deadzone (110<->140) causing the camera not to move, this needs to move the mouse faster for the Right joystick to pass the deadzone , this hover will be inaccurate and will feel a big delay

**Comment by r57zone** [comment]
Thanks for the Pull Request, I will add an optional dead zone change and update the binaries in the next few days.

**Pull request merged**
